Add missing include
CMXParser.cpp:42:43: error: expected ')'
    CDR_DEBUG_MSG(("invalid tag length %" PRIu16 "\n", tagLength));
                                          ^
CMXParser.cpp:42:19: note: to match this '('
    CDR_DEBUG_MSG(("invalid tag length %" PRIu16 "\n", tagLength));
                  ^
1 error generated.

Change-Id: I9575a96327a62dc6c44950d35a8740242e1a4433